// <auto-generated />
namespace MvcOnlineTradingAutomation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class employeenum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeenum));
        
        string IMigrationMetadata.Id
        {
            get { return "202502171317065_employeenum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
