// <auto-generated />
namespace MvcOnlineTradingAutomation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mg7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg7));
        
        string IMigrationMetadata.Id
        {
            get { return "202502141345243_mg7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
